version: "3.8"

services:
  backend_app:
    build: .
    container_name: backend_container
    ports:
      - "8000:401"
    environment:
      - SIEVE_API_KEY=value
    volumes:
      - .:/app
    restart: unless-stopped
